### ISSUE TITLE
Mock accepts content type "application/json", while DeepL API rejects it

### ISSUE THREAD

**Issue by DevViktorKovacs** [DeepLcom/deepl-mock#3]
I just ran into a serious issue with this mock server. 

I developed an application which worked perfectly fine while calling the locally hosted mock server, but as soon as I switched it to the production DeepL API I started getting bad request errors. 

The problem was that this mock accepts requests with content type "application/json" while the actual API only works with application/x-www-form-urlencoded, so I had to rework the entire data conversion logic...

**Comment by ghost** [comment]
Hi @DevViktorKovacs, thanks for creating this issue; sorry that you ran into this problem and it costed you time. I'll push a fix soon.

**Comment by ghost** [comment]
This is fixed in [v1.8.1](https://github.com/DeepLcom/deepl-mock/releases/tag/v1.8.1).

**Comment by DevViktorKovacs** [comment]
> This is fixed in [v1.8.1](https://github.com/DeepLcom/deepl-mock/releases/tag/v1.8.1).

That was quick! Thank you very much Daniel!
